server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:13366/railway
    username: postgres
    password: MreWuwVRbcyMzrereoYdkpLyjSBGibkO
    name: spring-blog
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
